In [33]:
import pandas as pd
import numpy as np

In [34]:
Fifa = pd.read_csv("Fifa 23 Players Data.csv")
Fifa

,Known As,Full Name,Overall,Potential,Value(in Euro),Positions Played,Best Position,Nationality,Image Link,Age,...,LM Rating,CM Rating,RM Rating,LWB Rating,CDM Rating,RWB Rating,LB Rating,CB Rating,RB Rating,GK Rating
0,L. Messi,Lionel Messi,91,91,54000000,RW,CAM,Argentina,https://cdn.sofifa.net/players/158/023/23_60.png,35,...,91,88,91,67,66,67,62,53,62,22
1,K. Benzema,Karim Benzema,91,91,64000000,"CF,ST",CF,France,https://cdn.sofifa.net/players/165/153/23_60.png,34,...,89,84,89,67,67,67,63,58,63,21
2,R. Lewandowski,Robert Lewandowski,91,91,84000000,ST,ST,Poland,https://cdn.sofifa.net/players/188/545/23_60.png,33,...,86,83,86,67,69,67,64,63,64,22
3,K. De Bruyne,Kevin De Bruyne,91,91,107500000,"CM,CAM",CM,Belgium,https://cdn.sofifa.net/players/192/985/23_60.png,31,...,91,91,91,82,82,82,78,72,78,24
4,K. Mbappé,Kylian Mbappé,91,95,190500000,"ST,LW",ST,France,https://cdn.sofifa.net/players/231/747/23_60.png,23,...,92,84,92,70,66,70,66,57,66,21
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
18534,D. Collins,Darren Collins,47,56,110000,"ST,RM",CAM,Republic of Ireland,https://cdn.sofifa.net/players/243/725/23_60.png,21,...,50,44,50,41,38,41,40,36,40,15
18535,Yang Dejiang,Dejiang Yang,47,57,90000,CDM,CDM,China PR,https://cdn.sofifa.net/players/261/933/23_60.png,17,...,45,45,45,47,48,47,49,49,49,15
18536,L. Mullan,Liam Mullan,47,67,130000,CM,RM,Northern Ireland,https://cdn.sofifa.net/players/267/823/23_60.png,18,...,52,49,52,46,44,46,46,42,46,17
18537,D. McCallion,Daithí McCallion,47,61,100000,CB,CB,Republic of Ireland,https://cdn.sofifa.net/players/267/824/23_60.png,17,...,33,33,33,44,42,44,47,49,47,15
18538,N. Rabha,Nabin Rabha,47,50,60000,LB,LB,India,https://cdn.sofifa.net/players/261/424/23_60.png,25,...,44,40,44,46,43,46,47,47,47,19

In [35]:
Fifa.columns

Index(['Known As', 'Full Name', 'Overall', 'Potential', 'Value(in Euro)',
       'Positions Played', 'Best Position', 'Nationality', 'Image Link', 'Age',
       'Height(in cm)', 'Weight(in kg)', 'TotalStats', 'BaseStats',
       'Club Name', 'Wage(in Euro)', 'Release Clause', 'Club Position',
       'Contract Until', 'Club Jersey Number', 'Joined On', 'On Loan',
       'Preferred Foot', 'Weak Foot Rating', 'Skill Moves',
       'International Reputation', 'National Team Name',
       'National Team Image Link', 'National Team Position',
       'National Team Jersey Number', 'Attacking Work Rate',
       'Defensive Work Rate', 'Pace Total', 'Shooting Total', 'Passing Total',
       'Dribbling Total', 'Defending Total', 'Physicality Total', 'Crossing',
       'Finishing', 'Heading Accuracy', 'Short Passing', 'Volleys',
       'Dribbling', 'Curve', 'Freekick Accuracy', 'LongPassing', 'BallControl',
       'Acceleration', 'Sprint Speed', 'Agility', 'Reactions', 'Balance',
       'Shot Power', 'Jumping', 'Stamina', 'Strength', 'Long Shots',
       'Aggression', 'Interceptions', 'Positioning', 'Vision', 'Penalties',
       'Composure', 'Marking', 'Standing Tackle', 'Sliding Tackle',
       'Goalkeeper Diving', 'Goalkeeper Handling', ' GoalkeeperKicking',
       'Goalkeeper Positioning', 'Goalkeeper Reflexes', 'ST Rating',
       'LW Rating', 'LF Rating', 'CF Rating', 'RF Rating', 'RW Rating',
       'CAM Rating', 'LM Rating', 'CM Rating', 'RM Rating', 'LWB Rating',
       'CDM Rating', 'RWB Rating', 'LB Rating', 'CB Rating', 'RB Rating',
       'GK Rating'],
      dtype='object')

In [36]:
# Cleaning the data by selecting the columns we will use for our analysis.

Fifa_Cle = Fifa[['Known As', 'Overall', 'Potential', 'Value(in Euro)',
       'Positions Played', 'Best Position', 'Age',
       'Height(in cm)', 'Weight(in kg)',
       'Club Name', 'Wage(in Euro)', 'Release Clause', 'Club Position',
       'Contract Until', 'Joined On', 'On Loan', 'National Team Name','ST Rating',
       'LW Rating', 'LF Rating', 'CF Rating', 'RF Rating', 'RW Rating',
       'CAM Rating', 'LM Rating', 'CM Rating', 'RM Rating', 'LWB Rating',
       'CDM Rating', 'RWB Rating', 'LB Rating', 'CB Rating', 'RB Rating',
       'GK Rating','Nationality']]

In [37]:
# Add a column to understand the potential gap of each player.

Fifa_Cle["Gap_Potential"] = Fifa_Cle["Potential"] - Fifa_Cle["Overall"]
Fifa_Cle

<ipython-input-37-3fcccea7f742>:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  Fifa_Cle["Gap_Potential"] = Fifa_Cle["Potential"] - Fifa_Cle["Overall"]

,Known As,Overall,Potential,Value(in Euro),Positions Played,Best Position,Age,Height(in cm),Weight(in kg),Club Name,...,RM Rating,LWB Rating,CDM Rating,RWB Rating,LB Rating,CB Rating,RB Rating,GK Rating,Nationality,Gap_Potential
0,L. Messi,91,91,54000000,RW,CAM,35,169,67,Paris Saint-Germain,...,91,67,66,67,62,53,62,22,Argentina,0
1,K. Benzema,91,91,64000000,"CF,ST",CF,34,185,81,Real Madrid CF,...,89,67,67,67,63,58,63,21,France,0
2,R. Lewandowski,91,91,84000000,ST,ST,33,185,81,FC Barcelona,...,86,67,69,67,64,63,64,22,Poland,0
3,K. De Bruyne,91,91,107500000,"CM,CAM",CM,31,181,70,Manchester City,...,91,82,82,82,78,72,78,24,Belgium,0
4,K. Mbappé,91,95,190500000,"ST,LW",ST,23,182,73,Paris Saint-Germain,...,92,70,66,70,66,57,66,21,France,4
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
18534,D. Collins,47,56,110000,"ST,RM",CAM,21,174,68,Sligo Rovers,...,50,41,38,41,40,36,40,15,Republic of Ireland,9
18535,Yang Dejiang,47,57,90000,CDM,CDM,17,175,60,Guangzhou FC,...,45,47,48,47,49,49,49,15,China PR,10
18536,L. Mullan,47,67,130000,CM,RM,18,170,65,Derry City,...,52,46,44,46,46,42,46,17,Northern Ireland,20
18537,D. McCallion,47,61,100000,CB,CB,17,178,65,Derry City,...,33,44,42,44,47,49,47,15,Republic of Ireland,14
18538,N. Rabha,47,50,60000,LB,LB,25,176,66,NorthEast United FC,...,44,46,43,46,47,47,47,19,India,3

In [38]:
#Get the data of all the players at Manchester City to have an overview of the players scores and potentials.

Fifa_MC = Fifa_Cle.loc[Fifa_Cle['Club Name'] == "Manchester City"]
Fifa_MC

,Known As,Overall,Potential,Value(in Euro),Positions Played,Best Position,Age,Height(in cm),Weight(in kg),Club Name,...,RM Rating,LWB Rating,CDM Rating,RWB Rating,LB Rating,CB Rating,RB Rating,GK Rating,Nationality,Gap_Potential
3,K. De Bruyne,91,91,107500000,"CM,CAM",CM,31,181,70,Manchester City,...,91,82,82,82,78,72,78,24,Belgium,0
16,Ederson,89,91,88000000,GK,GK,28,188,86,Manchester City,...,47,40,47,40,39,38,39,90,Brazil,2
20,Rúben Dias,88,91,107500000,CB,CB,25,187,82,Manchester City,...,67,81,86,81,83,90,83,21,Portugal,3
21,E. Haaland,88,94,148000000,ST,ST,21,195,94,Manchester City,...,80,65,67,65,64,65,64,22,Norway,6
23,Bernardo Silva,88,88,97500000,"CAM,CM",CAM,27,173,64,Manchester City,...,88,79,77,79,75,67,75,21,Portugal,0
24,João Cancelo,88,88,82500000,"LB,RB",LB,28,182,74,Manchester City,...,88,88,86,88,87,82,87,22,Portugal,0
31,Rodri,87,89,88500000,CDM,CDM,26,191,82,Manchester City,...,79,82,87,82,82,85,82,21,Spain,2
48,R. Mahrez,86,86,56500000,"RW,RM",RW,31,179,67,Manchester City,...,86,67,64,67,62,52,62,21,Algeria,0
55,A. Laporte,86,87,64500000,CB,CB,28,191,85,Manchester City,...,70,80,85,80,81,87,81,21,Spain,1
68,İ. Gündoğan,85,85,44000000,"CM,CDM",CM,31,180,80,Manchester City,...,85,80,83,80,78,75,78,22,Germany,0
69,K. Walker,85,85,37500000,RB,RB,32,183,83,Manchester City,...,81,85,84,85,85,84,85,22,England,0
83,P. Foden,85,92,109500000,"LW,CF,CAM",CAM,22,171,69,Manchester City,...,87,75,74,75,72,62,72,22,England,7
103,J. Grealish,84,84,46000000,"LW,LM,CAM",LW,26,180,81,Manchester City,...,84,71,70,71,66,57,66,21,England,0
194,J. Stones,83,84,34500000,CB,CB,28,188,76,Manchester City,...,73,80,83,80,81,84,81,20,England,1
320,M. Akanji,81,82,26500000,CB,CB,26,187,91,Manchester City,...,70,78,82,78,80,82,80,19,Switzerland,1
361,K. Phillips,81,85,32000000,"CDM,CM",CDM,26,178,72,Manchester City,...,76,80,82,80,79,81,79,20,England,4
430,S. Ortega,80,80,14500000,GK,GK,29,185,88,Manchester City,...,39,35,40,35,34,35,34,80,Germany,0
680,J. Álvarez,78,86,32000000,"ST,RW,LW",CAM,22,173,71,Manchester City,...,81,69,69,69,67,64,67,19,Argentina,8
759,N. Aké,78,80,15000000,"CB,LB",CB,27,180,75,Manchester City,...,71,78,79,78,79,80,79,21,Netherlands,2
1972,Sergio Gómez,74,83,9000000,"LB,RM,LM",CAM,21,171,68,Manchester City,...,75,75,74,75,74,69,74,19,Spain,9
8072,C. Palmer,67,85,2700000,"RW,CAM,CF",CAM,20,189,74,Manchester City,...,68,59,57,59,57,52,57,17,England,18
9267,M. Rogers,66,82,2200000,"LW,RW",RM,19,187,80,Manchester City,...,67,57,54,57,55,50,55,18,England,16
10444,S. Carson,65,65,80000,GK,GK,36,190,86,Manchester City,...,27,26,27,26,26,29,26,65,England,0
14529,R. Lewis,61,82,1000000,RB,RB,17,175,70,Manchester City,...,55,60,54,60,61,59,61,19,England,21
15117,B. Knight,60,74,600000,RW,CAM,20,170,59,Manchester City,...,60,47,43,47,44,38,44,16,England,14
16308,A. Robertson,58,78,575000,CM,CAM,19,180,66,Manchester City,...,61,57,58,57,57,55,57,16,England,20
16314,J. Wilson-Esbrand,58,76,500000,LB,LB,19,176,65,Manchester City,...,56,58,53,58,58,56,58,16,England,18

In [39]:
# Get the data of all the players outside of Manchester City.

Fifa_Other = Fifa_Cle.loc[Fifa_Cle['Club Name'] != "Manchester City"]
Fifa_Other

,Known As,Overall,Potential,Value(in Euro),Positions Played,Best Position,Age,Height(in cm),Weight(in kg),Club Name,...,RM Rating,LWB Rating,CDM Rating,RWB Rating,LB Rating,CB Rating,RB Rating,GK Rating,Nationality,Gap_Potential
0,L. Messi,91,91,54000000,RW,CAM,35,169,67,Paris Saint-Germain,...,91,67,66,67,62,53,62,22,Argentina,0
1,K. Benzema,91,91,64000000,"CF,ST",CF,34,185,81,Real Madrid CF,...,89,67,67,67,63,58,63,21,France,0
2,R. Lewandowski,91,91,84000000,ST,ST,33,185,81,FC Barcelona,...,86,67,69,67,64,63,64,22,Poland,0
4,K. Mbappé,91,95,190500000,"ST,LW",ST,23,182,73,Paris Saint-Germain,...,92,70,66,70,66,57,66,21,France,4
5,M. Salah,90,90,115500000,RW,RW,30,175,71,Liverpool,...,90,74,71,74,70,61,70,25,Egypt,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
18534,D. Collins,47,56,110000,"ST,RM",CAM,21,174,68,Sligo Rovers,...,50,41,38,41,40,36,40,15,Republic of Ireland,9
18535,Yang Dejiang,47,57,90000,CDM,CDM,17,175,60,Guangzhou FC,...,45,47,48,47,49,49,49,15,China PR,10
18536,L. Mullan,47,67,130000,CM,RM,18,170,65,Derry City,...,52,46,44,46,46,42,46,17,Northern Ireland,20
18537,D. McCallion,47,61,100000,CB,CB,17,178,65,Derry City,...,33,44,42,44,47,49,47,15,Republic of Ireland,14
18538,N. Rabha,47,50,60000,LB,LB,25,176,66,NorthEast United FC,...,44,46,43,46,47,47,47,19,India,3

***ANALYSIS 1 - Determining players to transfer according to their overall and potential. ***

In [40]:
# Create a new DataFrame to focus on the ratings of all the players (in and out of MC)

Fifa_Other.columns

Index(['Known As', 'Overall', 'Potential', 'Value(in Euro)',
       'Positions Played', 'Best Position', 'Age', 'Height(in cm)',
       'Weight(in kg)', 'Club Name', 'Wage(in Euro)', 'Release Clause',
       'Club Position', 'Contract Until', 'Joined On', 'On Loan',
       'National Team Name', 'ST Rating', 'LW Rating', 'LF Rating',
       'CF Rating', 'RF Rating', 'RW Rating', 'CAM Rating', 'LM Rating',
       'CM Rating', 'RM Rating', 'LWB Rating', 'CDM Rating', 'RWB Rating',
       'LB Rating', 'CB Rating', 'RB Rating', 'GK Rating', 'Nationality',
       'Gap_Potential'],
      dtype='object')

In [41]:
Fifa_MP = Fifa_Cle[['Known As', 'Overall', 'Potential','Positions Played','Club Name',
       'Club Position', 'ST Rating', 'LW Rating', 'LF Rating',
       'CF Rating', 'RF Rating', 'RW Rating', 'CAM Rating', 'LM Rating',
       'CM Rating', 'RM Rating', 'LWB Rating', 'CDM Rating', 'RWB Rating',
       'LB Rating', 'CB Rating', 'RB Rating', 'GK Rating', 'Nationality',
       'Gap_Potential']]

In [42]:
# Add the mean value of the "Overall" column for each positions.
#With this code, we could get all the means of each rating per position.
#Estimating that most likely the overall score was already calculated according to the other ratings, we decided to focus on that column.

Fifa_MP.groupby(['Positions Played']).mean()

#Fifa_MP["Overall_Mean"] = Fifa_MP.groupby(['Club Position']).agg({"Overall":"mean"})
#Fifa_MP

<ipython-input-42-f51cec8c7f60>:5: FutureWarning: The default value of numeric_only in DataFrameGroupBy.mean is deprecated. In a future version, numeric_only will default to False. Either specify numeric_only or select only columns which should be valid for the function.
  Fifa_MP.groupby(['Positions Played']).mean()

,Overall,Potential,ST Rating,LW Rating,LF Rating,CF Rating,RF Rating,RW Rating,CAM Rating,LM Rating,CM Rating,RM Rating,LWB Rating,CDM Rating,RWB Rating,LB Rating,CB Rating,RB Rating,GK Rating,Gap_Potential
Positions Played,,,,,,,,,,,,,,,,,,,,
CAM,62.849462,71.451613,60.602151,62.311828,61.768817,61.768817,61.768817,62.311828,64.327957,63.913978,61.204301,63.913978,53.924731,52.483871,53.924731,51.704301,46.532258,51.704301,17.505376,8.602151
"CAM,CDM",61.285714,66.285714,60.142857,59.857143,60.285714,60.285714,60.285714,59.857143,62.714286,62.142857,62.571429,62.142857,60.857143,61.142857,60.857143,59.714286,58.857143,59.714286,18.285714,5.000000
"CAM,CDM,CM",69.200000,70.800000,66.600000,67.400000,67.400000,67.400000,67.400000,67.400000,69.600000,68.800000,69.600000,68.800000,65.400000,66.600000,65.400000,63.800000,60.800000,63.800000,18.400000,1.600000
"CAM,CF",69.193548,75.838710,66.064516,68.516129,67.870968,67.870968,67.870968,68.516129,70.516129,70.290323,67.516129,70.290323,58.903226,57.064516,58.903226,55.870968,49.258065,55.870968,18.741935,6.645161
"CAM,CF,CM",71.555556,74.888889,70.111111,70.555556,70.666667,70.666667,70.666667,70.555556,72.444444,72.333333,71.333333,72.333333,67.111111,67.111111,67.111111,65.555556,62.222222,65.555556,19.000000,3.333333
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
"ST,RW,CF",66.000000,72.500000,67.000000,66.500000,66.000000,66.000000,66.000000,66.500000,66.500000,67.000000,63.000000,67.000000,54.000000,49.500000,54.000000,50.000000,42.500000,50.000000,17.500000,6.500000
"ST,RW,CM",68.000000,77.000000,70.000000,68.000000,68.000000,68.000000,68.000000,68.000000,68.000000,69.000000,61.000000,69.000000,53.000000,50.000000,53.000000,50.000000,44.000000,50.000000,19.000000,9.000000
"ST,RW,LW",64.615385,70.730769,66.076923,64.230769,64.307692,64.307692,64.307692,64.230769,64.730769,64.730769,58.269231,64.730769,51.076923,48.307692,51.076923,49.076923,45.423077,49.076923,17.692308,6.115385
"ST,RW,RM",67.555556,71.222222,68.555556,65.777778,66.333333,66.333333,66.333333,65.777778,66.111111,66.222222,59.222222,66.222222,50.444444,47.333333,50.444444,47.777778,44.444444,47.777778,18.222222,3.666667
"ST,RWB",56.666667,60.666667,58.666667,58.000000,57.000000,57.000000,57.000000,58.000000,57.333333,59.000000,53.333333,59.000000,53.333333,49.666667,53.333333,53.000000,49.333333,53.000000,17.000000,4.000000

In [43]:
#Calculate the mean values for each position:
position_means = Fifa_MP.groupby(['Positions Played'])['Overall'].mean().reset_index()

#Rename the "Overall" column with the position_means DataFrame to "Mean Overall".
position_means.rename(columns={'Overall': 'Mean Overall'}, inplace=True)

#Merge the mean values back into your initial DataFrame based on the "Club Position" column:
Fifa_MP = Fifa_MP.merge(position_means, on='Positions Played', how='left')

Fifa_MP

,Known As,Overall,Potential,Positions Played,Club Name,Club Position,ST Rating,LW Rating,LF Rating,CF Rating,...,LWB Rating,CDM Rating,RWB Rating,LB Rating,CB Rating,RB Rating,GK Rating,Nationality,Gap_Potential,Mean Overall
0,L. Messi,91,91,RW,Paris Saint-Germain,RW,90,90,91,91,...,67,66,67,62,53,62,22,Argentina,0,65.040816
1,K. Benzema,91,91,"CF,ST",Real Madrid CF,CF,91,87,89,89,...,67,67,67,63,58,63,21,France,0,71.095238
2,R. Lewandowski,91,91,ST,FC Barcelona,ST,91,85,88,88,...,67,69,67,64,63,64,22,Poland,0,65.657941
3,K. De Bruyne,91,91,"CM,CAM",Manchester City,CM,86,88,87,87,...,82,82,82,78,72,78,24,Belgium,0,66.021186
4,K. Mbappé,91,95,"ST,LW",Paris Saint-Germain,ST,92,90,90,90,...,70,66,70,66,57,66,21,France,4,65.962121
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
18534,D. Collins,47,56,"ST,RM",Sligo Rovers,RES,49,50,50,50,...,41,38,41,40,36,40,15,Republic of Ireland,9,65.237500
18535,Yang Dejiang,47,57,CDM,Guangzhou FC,SUB,44,43,43,43,...,47,48,47,49,49,49,15,China PR,10,63.166023
18536,L. Mullan,47,67,CM,Derry City,SUB,48,49,49,49,...,46,44,46,46,42,46,17,Northern Ireland,20,62.662568
18537,D. McCallion,47,61,CB,Derry City,SUB,33,30,30,30,...,44,42,44,47,49,47,15,Republic of Ireland,14,66.445540
18538,N. Rabha,47,50,LB,NorthEast United FC,RES,41,42,40,40,...,46,43,46,47,47,47,19,India,3,65.231660

In [44]:
#Re-order the columns to have "Overall" next to "Mean Overall"

Fifa_MP.columns

Index(['Known As', 'Overall', 'Potential', 'Positions Played', 'Club Name',
       'Club Position', 'ST Rating', 'LW Rating', 'LF Rating', 'CF Rating',
       'RF Rating', 'RW Rating', 'CAM Rating', 'LM Rating', 'CM Rating',
       'RM Rating', 'LWB Rating', 'CDM Rating', 'RWB Rating', 'LB Rating',
       'CB Rating', 'RB Rating', 'GK Rating', 'Nationality', 'Gap_Potential',
       'Mean Overall'],
      dtype='object')

In [45]:
Fifa_MP = Fifa_MP[['Known As','Overall', 'Mean Overall','Potential','Positions Played','Club Position', 'Club Name', 'ST Rating',
       'LW Rating', 'LF Rating', 'CF Rating', 'RF Rating', 'RW Rating',
       'CAM Rating', 'LM Rating', 'CM Rating', 'RM Rating', 'LWB Rating',
       'CDM Rating', 'RWB Rating', 'LB Rating', 'CB Rating', 'RB Rating',
       'GK Rating', 'Nationality', 'Gap_Potential']]

Fifa_MP

,Known As,Overall,Mean Overall,Potential,Positions Played,Club Position,Club Name,ST Rating,LW Rating,LF Rating,...,RM Rating,LWB Rating,CDM Rating,RWB Rating,LB Rating,CB Rating,RB Rating,GK Rating,Nationality,Gap_Potential
0,L. Messi,91,65.040816,91,RW,RW,Paris Saint-Germain,90,90,91,...,91,67,66,67,62,53,62,22,Argentina,0
1,K. Benzema,91,71.095238,91,"CF,ST",CF,Real Madrid CF,91,87,89,...,89,67,67,67,63,58,63,21,France,0
2,R. Lewandowski,91,65.657941,91,ST,ST,FC Barcelona,91,85,88,...,86,67,69,67,64,63,64,22,Poland,0
3,K. De Bruyne,91,66.021186,91,"CM,CAM",CM,Manchester City,86,88,87,...,91,82,82,82,78,72,78,24,Belgium,0
4,K. Mbappé,91,65.962121,95,"ST,LW",ST,Paris Saint-Germain,92,90,90,...,92,70,66,70,66,57,66,21,France,4
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
18534,D. Collins,47,65.237500,56,"ST,RM",RES,Sligo Rovers,49,50,50,...,50,41,38,41,40,36,40,15,Republic of Ireland,9
18535,Yang Dejiang,47,63.166023,57,CDM,SUB,Guangzhou FC,44,43,43,...,45,47,48,47,49,49,49,15,China PR,10
18536,L. Mullan,47,62.662568,67,CM,SUB,Derry City,48,49,49,...,52,46,44,46,46,42,46,17,Northern Ireland,20
18537,D. McCallion,47,66.445540,61,CB,SUB,Derry City,33,30,30,...,33,44,42,44,47,49,47,15,Republic of Ireland,14
18538,N. Rabha,47,65.231660,50,LB,RES,NorthEast United FC,41,42,40,...,44,46,43,46,47,47,47,19,India,3

In [46]:
Fifa_MC = Fifa_MP.loc[Fifa_MP['Club Name'] == "Manchester City"]
Fifa_MC

,Known As,Overall,Mean Overall,Potential,Positions Played,Club Position,Club Name,ST Rating,LW Rating,LF Rating,...,RM Rating,LWB Rating,CDM Rating,RWB Rating,LB Rating,CB Rating,RB Rating,GK Rating,Nationality,Gap_Potential
3,K. De Bruyne,91,66.021186,91,"CM,CAM",CM,Manchester City,86,88,87,...,91,82,82,82,78,72,78,24,Belgium,0
16,Ederson,89,64.453178,91,GK,GK,Manchester City,43,41,43,...,47,40,47,40,39,38,39,90,Brazil,2
20,Rúben Dias,88,66.445540,91,CB,CB,Manchester City,64,59,60,...,67,81,86,81,83,90,83,21,Portugal,3
21,E. Haaland,88,65.657941,94,ST,ST,Manchester City,90,80,84,...,80,65,67,65,64,65,64,22,Norway,6
23,Bernardo Silva,88,66.387597,88,"CAM,CM",RW,Manchester City,80,86,84,...,88,79,77,79,75,67,75,21,Portugal,0
24,João Cancelo,88,65.800000,88,"LB,RB",LB,Manchester City,81,84,83,...,88,88,86,88,87,82,87,22,Portugal,0
31,Rodri,87,63.166023,89,CDM,CDM,Manchester City,79,74,77,...,79,82,87,82,82,85,82,21,Spain,2
48,R. Mahrez,86,69.339623,86,"RW,RM",SUB,Manchester City,83,85,85,...,86,67,64,67,62,52,62,21,Algeria,0
55,A. Laporte,86,66.445540,87,CB,CB,Manchester City,69,64,66,...,70,80,85,80,81,87,81,21,Spain,1
68,İ. Gündoğan,85,67.120235,85,"CM,CDM",CM,Manchester City,81,82,82,...,85,80,83,80,78,75,78,22,Germany,0
69,K. Walker,85,65.377871,85,RB,RB,Manchester City,77,76,76,...,81,85,84,85,85,84,85,22,England,0
83,P. Foden,85,77.500000,92,"LW,CF,CAM",LW,Manchester City,80,84,83,...,87,75,74,75,72,62,72,22,England,7
103,J. Grealish,84,69.250000,84,"LW,LM,CAM",SUB,Manchester City,78,83,81,...,84,71,70,71,66,57,66,21,England,0
194,J. Stones,83,66.445540,84,CB,SUB,Manchester City,69,69,69,...,73,80,83,80,81,84,81,20,England,1
320,M. Akanji,81,66.445540,82,CB,SUB,Manchester City,66,65,65,...,70,78,82,78,80,82,80,19,Switzerland,1
361,K. Phillips,81,67.414481,85,"CDM,CM",SUB,Manchester City,72,72,72,...,76,80,82,80,79,81,79,20,England,4
430,S. Ortega,80,64.453178,80,GK,SUB,Manchester City,37,34,37,...,39,35,40,35,34,35,34,80,Germany,0
680,J. Álvarez,78,64.615385,86,"ST,RW,LW",SUB,Manchester City,80,80,80,...,81,69,69,69,67,64,67,19,Argentina,8
759,N. Aké,78,66.200000,80,"CB,LB",SUB,Manchester City,68,67,66,...,71,78,79,78,79,80,79,21,Netherlands,2
1972,Sergio Gómez,74,69.500000,83,"LB,RM,LM",SUB,Manchester City,70,73,72,...,75,75,74,75,74,69,74,19,Spain,9
8072,C. Palmer,67,67.000000,85,"RW,CAM,CF",SUB,Manchester City,65,67,66,...,68,59,57,59,57,52,57,17,England,18
9267,M. Rogers,66,66.170000,82,"LW,RW",RES,Manchester City,66,66,65,...,67,57,54,57,55,50,55,18,England,16
10444,S. Carson,65,64.453178,65,GK,SUB,Manchester City,30,25,27,...,27,26,27,26,26,29,26,65,England,0
14529,R. Lewis,61,65.377871,82,RB,SUB,Manchester City,50,53,50,...,55,60,54,60,61,59,61,19,England,21
15117,B. Knight,60,65.040816,74,RW,RES,Manchester City,58,60,59,...,60,47,43,47,44,38,44,16,England,14
16308,A. Robertson,58,62.662568,78,CM,RES,Manchester City,58,57,58,...,61,57,58,57,57,55,57,16,England,20
16314,J. Wilson-Esbrand,58,65.231660,76,LB,RES,Manchester City,49,53,50,...,56,58,53,58,58,56,58,16,England,18

In [47]:
"""

This is where we realized that we only have substitutes and reserve club positions players with an overall score below the mean score of all the other players.
We took the decision to instead take the mean of the Top 10 champions league teams of 2023-2024 which are the following:

1. Manchester City
2. Real Madrid
3. FC Barcelona
4. Bayern Munich
5. Inter
6. Real Sociedad
7. Arsenal
8. PSG
9. Atletico de Madrid
10. Porto

"""

'\n\nThis is where we realized that we only have substitutes and reserve club positions players with an overall score below the mean score of all the other players.\nWe took the decision to instead take the mean of the Top 10 champions league teams of 2023-2024 which are the following:\n\n1. Manchester City\n2. Real Madrid\n3. FC Barcelona\n4. Bayern Munich\n5. Inter\n6. Real Sociedad\n7. Arsenal\n8. PSG\n9. Atletico de Madrid\n10. Porto\n\n'

In [48]:
#Creating a new DataFrame with the data of the top 10 teams in our Champions league ranking.

Fifa_Champions = Fifa[Fifa['Club Name'].isin(["Manchester City", "Real Madrid", "FC Barcelona","Bayern Munich","Inter","Real Sociedad", "Arsenal","Paris Saint-Germain", "Atletico de Madrid","Porto"])]

Fifa_Champions

,Known As,Full Name,Overall,Potential,Value(in Euro),Positions Played,Best Position,Nationality,Image Link,Age,...,LM Rating,CM Rating,RM Rating,LWB Rating,CDM Rating,RWB Rating,LB Rating,CB Rating,RB Rating,GK Rating
0,L. Messi,Lionel Messi,91,91,54000000,RW,CAM,Argentina,https://cdn.sofifa.net/players/158/023/23_60.png,35,...,91,88,91,67,66,67,62,53,62,22
2,R. Lewandowski,Robert Lewandowski,91,91,84000000,ST,ST,Poland,https://cdn.sofifa.net/players/188/545/23_60.png,33,...,86,83,86,67,69,67,64,63,64,22
3,K. De Bruyne,Kevin De Bruyne,91,91,107500000,"CM,CAM",CM,Belgium,https://cdn.sofifa.net/players/192/985/23_60.png,31,...,91,91,91,82,82,82,78,72,78,24
4,K. Mbappé,Kylian Mbappé,91,95,190500000,"ST,LW",ST,France,https://cdn.sofifa.net/players/231/747/23_60.png,23,...,92,84,92,70,66,70,66,57,66,21
11,Neymar Jr,Neymar da Silva Santos Jr.,89,89,99500000,LW,LW,Brazil,https://cdn.sofifa.net/players/190/871/23_60.png,30,...,89,85,89,69,66,69,64,53,64,23
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
15117,B. Knight,Ben Knight,60,74,600000,RW,CAM,England,https://cdn.sofifa.net/players/263/955/23_60.png,20,...,60,53,60,47,43,47,44,38,44,16
15912,A. Cozier-Duberry,Amario Cozier-Duberry,59,78,550000,"LM,CAM",LM,England,https://cdn.sofifa.net/players/271/743/23_60.png,17,...,60,53,60,48,44,48,45,39,45,17
16308,A. Robertson,Alex Robertson,58,78,575000,CM,CAM,England,https://cdn.sofifa.net/players/259/677/23_60.png,19,...,61,60,61,57,58,57,57,55,57,16
16314,J. Wilson-Esbrand,Joshua Wilson-Esbrand,58,76,500000,LB,LB,England,https://cdn.sofifa.net/players/264/681/23_60.png,19,...,56,50,56,58,53,58,58,56,58,16
16986,L. Sousa,Lino Sousa,56,80,425000,LB,LB,England,https://cdn.sofifa.net/players/271/808/23_60.png,17,...,52,48,52,56,52,56,56,56,56,17

In [49]:
#Calculate the mean values for each position:
position_means2 = Fifa_Champions.groupby(['Positions Played'])['Overall'].mean().reset_index()

#Rename the "Overall" column with the position_means DataFrame to "Mean Overall".
position_means2.rename(columns={'Overall': 'Mean Overall'}, inplace=True)

#Merge the mean values back into your initial DataFrame based on the "Club Position" column:
Fifa_Champions = Fifa_Champions.merge(position_means2, on='Positions Played', how='left')

Fifa_Champions

,Known As,Full Name,Overall,Potential,Value(in Euro),Positions Played,Best Position,Nationality,Image Link,Age,...,CM Rating,RM Rating,LWB Rating,CDM Rating,RWB Rating,LB Rating,CB Rating,RB Rating,GK Rating,Mean Overall
0,L. Messi,Lionel Messi,91,91,54000000,RW,CAM,Argentina,https://cdn.sofifa.net/players/158/023/23_60.png,35,...,88,91,67,66,67,62,53,62,22,70.000000
1,R. Lewandowski,Robert Lewandowski,91,91,84000000,ST,ST,Poland,https://cdn.sofifa.net/players/188/545/23_60.png,33,...,83,86,67,69,67,64,63,64,22,79.454545
2,K. De Bruyne,Kevin De Bruyne,91,91,107500000,"CM,CAM",CM,Belgium,https://cdn.sofifa.net/players/192/985/23_60.png,31,...,91,91,82,82,82,78,72,78,24,85.666667
3,K. Mbappé,Kylian Mbappé,91,95,190500000,"ST,LW",ST,France,https://cdn.sofifa.net/players/231/747/23_60.png,23,...,84,92,70,66,70,66,57,66,21,77.000000
4,Neymar Jr,Neymar da Silva Santos Jr.,89,89,99500000,LW,LW,Brazil,https://cdn.sofifa.net/players/190/871/23_60.png,30,...,85,89,69,66,69,64,53,64,23,80.666667
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
168,B. Knight,Ben Knight,60,74,600000,RW,CAM,England,https://cdn.sofifa.net/players/263/955/23_60.png,20,...,53,60,47,43,47,44,38,44,16,70.000000
169,A. Cozier-Duberry,Amario Cozier-Duberry,59,78,550000,"LM,CAM",LM,England,https://cdn.sofifa.net/players/271/743/23_60.png,17,...,53,60,48,44,48,45,39,45,17,69.500000
170,A. Robertson,Alex Robertson,58,78,575000,CM,CAM,England,https://cdn.sofifa.net/players/259/677/23_60.png,19,...,60,61,57,58,57,57,55,57,16,79.857143
171,J. Wilson-Esbrand,Joshua Wilson-Esbrand,58,76,500000,LB,LB,England,https://cdn.sofifa.net/players/264/681/23_60.png,19,...,50,56,58,53,58,58,56,58,16,73.400000
172,L. Sousa,Lino Sousa,56,80,425000,LB,LB,England,https://cdn.sofifa.net/players/271/808/23_60.png,17,...,48,52,56,52,56,56,56,56,17,73.400000

In [50]:
Fifa_Champions.columns

Index(['Known As', 'Full Name', 'Overall', 'Potential', 'Value(in Euro)',
       'Positions Played', 'Best Position', 'Nationality', 'Image Link', 'Age',
       'Height(in cm)', 'Weight(in kg)', 'TotalStats', 'BaseStats',
       'Club Name', 'Wage(in Euro)', 'Release Clause', 'Club Position',
       'Contract Until', 'Club Jersey Number', 'Joined On', 'On Loan',
       'Preferred Foot', 'Weak Foot Rating', 'Skill Moves',
       'International Reputation', 'National Team Name',
       'National Team Image Link', 'National Team Position',
       'National Team Jersey Number', 'Attacking Work Rate',
       'Defensive Work Rate', 'Pace Total', 'Shooting Total', 'Passing Total',
       'Dribbling Total', 'Defending Total', 'Physicality Total', 'Crossing',
       'Finishing', 'Heading Accuracy', 'Short Passing', 'Volleys',
       'Dribbling', 'Curve', 'Freekick Accuracy', 'LongPassing', 'BallControl',
       'Acceleration', 'Sprint Speed', 'Agility', 'Reactions', 'Balance',
       'Shot Power', 'Jumping', 'Stamina', 'Strength', 'Long Shots',
       'Aggression', 'Interceptions', 'Positioning', 'Vision', 'Penalties',
       'Composure', 'Marking', 'Standing Tackle', 'Sliding Tackle',
       'Goalkeeper Diving', 'Goalkeeper Handling', ' GoalkeeperKicking',
       'Goalkeeper Positioning', 'Goalkeeper Reflexes', 'ST Rating',
       'LW Rating', 'LF Rating', 'CF Rating', 'RF Rating', 'RW Rating',
       'CAM Rating', 'LM Rating', 'CM Rating', 'RM Rating', 'LWB Rating',
       'CDM Rating', 'RWB Rating', 'LB Rating', 'CB Rating', 'RB Rating',
       'GK Rating', 'Mean Overall'],
      dtype='object')

In [51]:
Fifa_Champions = Fifa_Champions[['Known As', 'Overall','Mean Overall', 'Potential','Positions Played','Club Name', 'Value(in Euro)','Age', 'Best Position', 'Wage(in Euro)', 'Release Clause',
       'Club Position', 'Contract Until', 'Joined On', 'On Loan',
       'National Team Name', 'ST Rating', 'LW Rating', 'LF Rating',
       'CF Rating', 'RF Rating', 'RW Rating', 'CAM Rating', 'LM Rating',
       'CM Rating', 'RM Rating', 'LWB Rating', 'CDM Rating', 'RWB Rating',
       'LB Rating', 'CB Rating', 'RB Rating', 'GK Rating', 'Nationality']]

Fifa_Champions

,Known As,Overall,Mean Overall,Potential,Positions Played,Club Name,Value(in Euro),Age,Best Position,Wage(in Euro),...,CM Rating,RM Rating,LWB Rating,CDM Rating,RWB Rating,LB Rating,CB Rating,RB Rating,GK Rating,Nationality
0,L. Messi,91,70.000000,91,RW,Paris Saint-Germain,54000000,35,CAM,195000,...,88,91,67,66,67,62,53,62,22,Argentina
1,R. Lewandowski,91,79.454545,91,ST,FC Barcelona,84000000,33,ST,420000,...,83,86,67,69,67,64,63,64,22,Poland
2,K. De Bruyne,91,85.666667,91,"CM,CAM",Manchester City,107500000,31,CM,350000,...,91,91,82,82,82,78,72,78,24,Belgium
3,K. Mbappé,91,77.000000,95,"ST,LW",Paris Saint-Germain,190500000,23,ST,230000,...,84,92,70,66,70,66,57,66,21,France
4,Neymar Jr,89,80.666667,89,LW,Paris Saint-Germain,99500000,30,LW,200000,...,85,89,69,66,69,64,53,64,23,Brazil
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
168,B. Knight,60,70.000000,74,RW,Manchester City,600000,20,CAM,12000,...,53,60,47,43,47,44,38,44,16,England
169,A. Cozier-Duberry,59,69.500000,78,"LM,CAM",Arsenal,550000,17,LM,1000,...,53,60,48,44,48,45,39,45,17,England
170,A. Robertson,58,79.857143,78,CM,Manchester City,575000,19,CAM,8000,...,60,61,57,58,57,57,55,57,16,England
171,J. Wilson-Esbrand,58,73.400000,76,LB,Manchester City,500000,19,LB,7000,...,50,56,58,53,58,58,56,58,16,England
172,L. Sousa,56,73.400000,80,LB,Arsenal,425000,17,LB,500,...,48,52,56,52,56,56,56,56,17,England

In [52]:
#Checking again the overall score of our players in Manchester City compared to the mean of the Champions League top teams.

Fifa_MC2 = Fifa_Champions.loc[Fifa_Champions['Club Name'] == "Manchester City"]
Fifa_MC2

,Known As,Overall,Mean Overall,Potential,Positions Played,Club Name,Value(in Euro),Age,Best Position,Wage(in Euro),...,CM Rating,RM Rating,LWB Rating,CDM Rating,RWB Rating,LB Rating,CB Rating,RB Rating,GK Rating,Nationality
2,K. De Bruyne,91,85.666667,91,"CM,CAM",Manchester City,107500000,31,CM,350000,...,91,91,82,82,82,78,72,78,24,Belgium
5,Ederson,89,76.473684,91,GK,Manchester City,88000000,28,GK,210000,...,52,47,40,47,40,39,38,39,90,Brazil
6,Rúben Dias,88,80.083333,91,CB,Manchester City,107500000,25,CB,230000,...,73,67,81,86,81,83,90,83,21,Portugal
7,E. Haaland,88,79.454545,94,ST,Manchester City,148000000,21,ST,220000,...,76,80,65,67,65,64,65,64,22,Norway
9,Bernardo Silva,88,84.000000,88,"CAM,CM",Manchester City,97500000,27,CAM,260000,...,86,88,79,77,79,75,67,75,21,Portugal
10,João Cancelo,88,88.000000,88,"LB,RB",Manchester City,82500000,28,LB,250000,...,87,88,88,86,88,87,82,87,22,Portugal
14,Rodri,87,79.000000,89,CDM,Manchester City,88500000,26,CDM,200000,...,86,79,82,87,82,82,85,82,21,Spain
18,R. Mahrez,86,84.500000,86,"RW,RM",Manchester City,56500000,31,RW,220000,...,81,86,67,64,67,62,52,62,21,Algeria
19,A. Laporte,86,80.083333,87,CB,Manchester City,64500000,28,CB,195000,...,77,70,80,85,80,81,87,81,21,Spain
24,İ. Gündoğan,85,73.555556,85,"CM,CDM",Manchester City,44000000,31,CM,185000,...,85,85,80,83,80,78,75,78,22,Germany
25,K. Walker,85,76.000000,85,RB,Manchester City,37500000,32,RB,170000,...,81,81,85,84,85,85,84,85,22,England
30,P. Foden,85,85.000000,92,"LW,CF,CAM",Manchester City,109500000,22,CAM,180000,...,85,87,75,74,75,72,62,72,22,England
35,J. Grealish,84,84.000000,84,"LW,LM,CAM",Manchester City,46000000,26,LW,185000,...,83,84,71,70,71,66,57,66,21,England
54,J. Stones,83,80.083333,84,CB,Manchester City,34500000,28,CB,150000,...,76,73,80,83,80,81,84,81,20,England
66,M. Akanji,81,80.083333,82,CB,Manchester City,26500000,26,CB,120000,...,74,70,78,82,78,80,82,80,19,Switzerland
71,K. Phillips,81,79.777778,85,"CDM,CM",Manchester City,32000000,26,CDM,120000,...,80,76,80,82,80,79,81,79,20,England
77,S. Ortega,80,76.473684,80,GK,Manchester City,14500000,29,GK,95000,...,43,39,35,40,35,34,35,34,80,Germany
92,J. Álvarez,78,78.000000,86,"ST,RW,LW",Manchester City,32000000,22,CAM,100000,...,78,81,69,69,69,67,64,67,19,Argentina
95,N. Aké,78,72.500000,80,"CB,LB",Manchester City,15000000,27,CB,95000,...,74,71,78,79,78,79,80,79,21,Netherlands
118,Sergio Gómez,74,74.000000,83,"LB,RM,LM",Manchester City,9000000,21,CAM,53000,...,75,75,75,74,75,74,69,74,19,Spain
147,C. Palmer,67,67.000000,85,"RW,CAM,CF",Manchester City,2700000,20,CAM,26000,...,64,68,59,57,59,57,52,57,17,England
149,M. Rogers,66,71.333333,82,"LW,RW",Manchester City,2200000,19,RM,17000,...,62,67,57,54,57,55,50,55,18,England
153,S. Carson,65,76.473684,65,GK,Manchester City,80000,36,GK,11000,...,28,27,26,27,26,26,29,26,65,England
167,R. Lewis,61,76.000000,82,RB,Manchester City,1000000,17,RB,650,...,49,55,60,54,60,61,59,61,19,England
168,B. Knight,60,70.000000,74,RW,Manchester City,600000,20,CAM,12000,...,53,60,47,43,47,44,38,44,16,England
170,A. Robertson,58,79.857143,78,CM,Manchester City,575000,19,CAM,8000,...,60,61,57,58,57,57,55,57,16,England
171,J. Wilson-Esbrand,58,73.400000,76,LB,Manchester City,500000,19,LB,7000,...,50,56,58,53,58,58,56,58,16,England

In [53]:
#As we also wanted to take into account the potential, we created a new column taking it inot account.

Fifa_MC2["Real_OScore"] = (Fifa_MC2["Overall"] + Fifa_MC2["Potential"])/ 2

Fifa_MC2

<ipython-input-53-d4affa8bf6f4>:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  Fifa_MC2["Real_OScore"] = (Fifa_MC2["Overall"] + Fifa_MC2["Potential"])/ 2

,Known As,Overall,Mean Overall,Potential,Positions Played,Club Name,Value(in Euro),Age,Best Position,Wage(in Euro),...,RM Rating,LWB Rating,CDM Rating,RWB Rating,LB Rating,CB Rating,RB Rating,GK Rating,Nationality,Real_OScore
2,K. De Bruyne,91,85.666667,91,"CM,CAM",Manchester City,107500000,31,CM,350000,...,91,82,82,82,78,72,78,24,Belgium,91.0
5,Ederson,89,76.473684,91,GK,Manchester City,88000000,28,GK,210000,...,47,40,47,40,39,38,39,90,Brazil,90.0
6,Rúben Dias,88,80.083333,91,CB,Manchester City,107500000,25,CB,230000,...,67,81,86,81,83,90,83,21,Portugal,89.5
7,E. Haaland,88,79.454545,94,ST,Manchester City,148000000,21,ST,220000,...,80,65,67,65,64,65,64,22,Norway,91.0
9,Bernardo Silva,88,84.000000,88,"CAM,CM",Manchester City,97500000,27,CAM,260000,...,88,79,77,79,75,67,75,21,Portugal,88.0
10,João Cancelo,88,88.000000,88,"LB,RB",Manchester City,82500000,28,LB,250000,...,88,88,86,88,87,82,87,22,Portugal,88.0
14,Rodri,87,79.000000,89,CDM,Manchester City,88500000,26,CDM,200000,...,79,82,87,82,82,85,82,21,Spain,88.0
18,R. Mahrez,86,84.500000,86,"RW,RM",Manchester City,56500000,31,RW,220000,...,86,67,64,67,62,52,62,21,Algeria,86.0
19,A. Laporte,86,80.083333,87,CB,Manchester City,64500000,28,CB,195000,...,70,80,85,80,81,87,81,21,Spain,86.5
24,İ. Gündoğan,85,73.555556,85,"CM,CDM",Manchester City,44000000,31,CM,185000,...,85,80,83,80,78,75,78,22,Germany,85.0
25,K. Walker,85,76.000000,85,RB,Manchester City,37500000,32,RB,170000,...,81,85,84,85,85,84,85,22,England,85.0
30,P. Foden,85,85.000000,92,"LW,CF,CAM",Manchester City,109500000,22,CAM,180000,...,87,75,74,75,72,62,72,22,England,88.5
35,J. Grealish,84,84.000000,84,"LW,LM,CAM",Manchester City,46000000,26,LW,185000,...,84,71,70,71,66,57,66,21,England,84.0
54,J. Stones,83,80.083333,84,CB,Manchester City,34500000,28,CB,150000,...,73,80,83,80,81,84,81,20,England,83.5
66,M. Akanji,81,80.083333,82,CB,Manchester City,26500000,26,CB,120000,...,70,78,82,78,80,82,80,19,Switzerland,81.5
71,K. Phillips,81,79.777778,85,"CDM,CM",Manchester City,32000000,26,CDM,120000,...,76,80,82,80,79,81,79,20,England,83.0
77,S. Ortega,80,76.473684,80,GK,Manchester City,14500000,29,GK,95000,...,39,35,40,35,34,35,34,80,Germany,80.0
92,J. Álvarez,78,78.000000,86,"ST,RW,LW",Manchester City,32000000,22,CAM,100000,...,81,69,69,69,67,64,67,19,Argentina,82.0
95,N. Aké,78,72.500000,80,"CB,LB",Manchester City,15000000,27,CB,95000,...,71,78,79,78,79,80,79,21,Netherlands,79.0
118,Sergio Gómez,74,74.000000,83,"LB,RM,LM",Manchester City,9000000,21,CAM,53000,...,75,75,74,75,74,69,74,19,Spain,78.5
147,C. Palmer,67,67.000000,85,"RW,CAM,CF",Manchester City,2700000,20,CAM,26000,...,68,59,57,59,57,52,57,17,England,76.0
149,M. Rogers,66,71.333333,82,"LW,RW",Manchester City,2200000,19,RM,17000,...,67,57,54,57,55,50,55,18,England,74.0
153,S. Carson,65,76.473684,65,GK,Manchester City,80000,36,GK,11000,...,27,26,27,26,26,29,26,65,England,65.0
167,R. Lewis,61,76.000000,82,RB,Manchester City,1000000,17,RB,650,...,55,60,54,60,61,59,61,19,England,71.5
168,B. Knight,60,70.000000,74,RW,Manchester City,600000,20,CAM,12000,...,60,47,43,47,44,38,44,16,England,67.0
170,A. Robertson,58,79.857143,78,CM,Manchester City,575000,19,CAM,8000,...,61,57,58,57,57,55,57,16,England,68.0
171,J. Wilson-Esbrand,58,73.400000,76,LB,Manchester City,500000,19,LB,7000,...,56,58,53,58,58,56,58,16,England,67.0

In [54]:
#Focusing our data on the columns needed to determine who we would like to transfer:

Fifa_MC2.columns

Index(['Known As', 'Overall', 'Mean Overall', 'Potential', 'Positions Played',
       'Club Name', 'Value(in Euro)', 'Age', 'Best Position', 'Wage(in Euro)',
       'Release Clause', 'Club Position', 'Contract Until', 'Joined On',
       'On Loan', 'National Team Name', 'ST Rating', 'LW Rating', 'LF Rating',
       'CF Rating', 'RF Rating', 'RW Rating', 'CAM Rating', 'LM Rating',
       'CM Rating', 'RM Rating', 'LWB Rating', 'CDM Rating', 'RWB Rating',
       'LB Rating', 'CB Rating', 'RB Rating', 'GK Rating', 'Nationality',
       'Real_OScore'],
      dtype='object')

In [55]:
Fifa_MC2 = Fifa_MC2[['Known As', 'Overall','Potential', 'Real_OScore','Mean Overall', 'Club Name',
       'Value(in Euro)','Positions Played', 'Club Position']]

Fifa_MC2

,Known As,Overall,Potential,Real_OScore,Mean Overall,Club Name,Value(in Euro),Positions Played,Club Position
2,K. De Bruyne,91,91,91.0,85.666667,Manchester City,107500000,"CM,CAM",CM
5,Ederson,89,91,90.0,76.473684,Manchester City,88000000,GK,GK
6,Rúben Dias,88,91,89.5,80.083333,Manchester City,107500000,CB,CB
7,E. Haaland,88,94,91.0,79.454545,Manchester City,148000000,ST,ST
9,Bernardo Silva,88,88,88.0,84.000000,Manchester City,97500000,"CAM,CM",RW
10,João Cancelo,88,88,88.0,88.000000,Manchester City,82500000,"LB,RB",LB
14,Rodri,87,89,88.0,79.000000,Manchester City,88500000,CDM,CDM
18,R. Mahrez,86,86,86.0,84.500000,Manchester City,56500000,"RW,RM",SUB
19,A. Laporte,86,87,86.5,80.083333,Manchester City,64500000,CB,CB
24,İ. Gündoğan,85,85,85.0,73.555556,Manchester City,44000000,"CM,CDM",CM
25,K. Walker,85,85,85.0,76.000000,Manchester City,37500000,RB,RB
30,P. Foden,85,92,88.5,85.000000,Manchester City,109500000,"LW,CF,CAM",LW
35,J. Grealish,84,84,84.0,84.000000,Manchester City,46000000,"LW,LM,CAM",SUB
54,J. Stones,83,84,83.5,80.083333,Manchester City,34500000,CB,SUB
66,M. Akanji,81,82,81.5,80.083333,Manchester City,26500000,CB,SUB
71,K. Phillips,81,85,83.0,79.777778,Manchester City,32000000,"CDM,CM",SUB
77,S. Ortega,80,80,80.0,76.473684,Manchester City,14500000,GK,SUB
92,J. Álvarez,78,86,82.0,78.000000,Manchester City,32000000,"ST,RW,LW",SUB
95,N. Aké,78,80,79.0,72.500000,Manchester City,15000000,"CB,LB",SUB
118,Sergio Gómez,74,83,78.5,74.000000,Manchester City,9000000,"LB,RM,LM",SUB
147,C. Palmer,67,85,76.0,67.000000,Manchester City,2700000,"RW,CAM,CF",SUB
149,M. Rogers,66,82,74.0,71.333333,Manchester City,2200000,"LW,RW",RES
153,S. Carson,65,65,65.0,76.473684,Manchester City,80000,GK,SUB
167,R. Lewis,61,82,71.5,76.000000,Manchester City,1000000,RB,SUB
168,B. Knight,60,74,67.0,70.000000,Manchester City,600000,RW,RES
170,A. Robertson,58,78,68.0,79.857143,Manchester City,575000,CM,RES
171,J. Wilson-Esbrand,58,76,67.0,73.400000,Manchester City,500000,LB,RES

In [56]:
#Creating a new column with a boolean analysis to highlight players with a Real_OScore below the mean of the Champions leage top 10 teams.

Fifa_MC2["A1_Transfer?"] = np.where(Fifa_MC2["Real_OScore"] < Fifa_MC2["Mean Overall"], True, False)
Fifa_MC2

<ipython-input-56-87ff3209f0de>:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  Fifa_MC2["A1_Transfer?"] = np.where(Fifa_MC2["Real_OScore"] < Fifa_MC2["Mean Overall"], True, False)

,Known As,Overall,Potential,Real_OScore,Mean Overall,Club Name,Value(in Euro),Positions Played,Club Position,A1_Transfer?
2,K. De Bruyne,91,91,91.0,85.666667,Manchester City,107500000,"CM,CAM",CM,False
5,Ederson,89,91,90.0,76.473684,Manchester City,88000000,GK,GK,False
6,Rúben Dias,88,91,89.5,80.083333,Manchester City,107500000,CB,CB,False
7,E. Haaland,88,94,91.0,79.454545,Manchester City,148000000,ST,ST,False
9,Bernardo Silva,88,88,88.0,84.000000,Manchester City,97500000,"CAM,CM",RW,False
10,João Cancelo,88,88,88.0,88.000000,Manchester City,82500000,"LB,RB",LB,False
14,Rodri,87,89,88.0,79.000000,Manchester City,88500000,CDM,CDM,False
18,R. Mahrez,86,86,86.0,84.500000,Manchester City,56500000,"RW,RM",SUB,False
19,A. Laporte,86,87,86.5,80.083333,Manchester City,64500000,CB,CB,False
24,İ. Gündoğan,85,85,85.0,73.555556,Manchester City,44000000,"CM,CDM",CM,False
25,K. Walker,85,85,85.0,76.000000,Manchester City,37500000,RB,RB,False
30,P. Foden,85,92,88.5,85.000000,Manchester City,109500000,"LW,CF,CAM",LW,False
35,J. Grealish,84,84,84.0,84.000000,Manchester City,46000000,"LW,LM,CAM",SUB,False
54,J. Stones,83,84,83.5,80.083333,Manchester City,34500000,CB,SUB,False
66,M. Akanji,81,82,81.5,80.083333,Manchester City,26500000,CB,SUB,False
71,K. Phillips,81,85,83.0,79.777778,Manchester City,32000000,"CDM,CM",SUB,False
77,S. Ortega,80,80,80.0,76.473684,Manchester City,14500000,GK,SUB,False
92,J. Álvarez,78,86,82.0,78.000000,Manchester City,32000000,"ST,RW,LW",SUB,False
95,N. Aké,78,80,79.0,72.500000,Manchester City,15000000,"CB,LB",SUB,False
118,Sergio Gómez,74,83,78.5,74.000000,Manchester City,9000000,"LB,RM,LM",SUB,False
147,C. Palmer,67,85,76.0,67.000000,Manchester City,2700000,"RW,CAM,CF",SUB,False
149,M. Rogers,66,82,74.0,71.333333,Manchester City,2200000,"LW,RW",RES,False
153,S. Carson,65,65,65.0,76.473684,Manchester City,80000,GK,SUB,True
167,R. Lewis,61,82,71.5,76.000000,Manchester City,1000000,RB,SUB,True
168,B. Knight,60,74,67.0,70.000000,Manchester City,600000,RW,RES,True
170,A. Robertson,58,78,68.0,79.857143,Manchester City,575000,CM,RES,True
171,J. Wilson-Esbrand,58,76,67.0,73.400000,Manchester City,500000,LB,RES,True

In [57]:
"""
According to this first analysis, the players to transfer are the following:

S. Carson, R. Lewis, B. Knight, A. Robertson, J. Wilson-Esbrand

"""

'\nAccording to this first analysis, the players to transfer are the following:\n\nS. Carson, R. Lewis, B. Knight, A. Robertson, J. Wilson-Esbrand\n\n'

***ANALYSIS 2 - Determining players to transfer according to their age and release date. ***

In [58]:
Fifa_Cle.columns

Index(['Known As', 'Overall', 'Potential', 'Value(in Euro)',
       'Positions Played', 'Best Position', 'Age', 'Height(in cm)',
       'Weight(in kg)', 'Club Name', 'Wage(in Euro)', 'Release Clause',
       'Club Position', 'Contract Until', 'Joined On', 'On Loan',
       'National Team Name', 'ST Rating', 'LW Rating', 'LF Rating',
       'CF Rating', 'RF Rating', 'RW Rating', 'CAM Rating', 'LM Rating',
       'CM Rating', 'RM Rating', 'LWB Rating', 'CDM Rating', 'RWB Rating',
       'LB Rating', 'CB Rating', 'RB Rating', 'GK Rating', 'Nationality',
       'Gap_Potential'],
      dtype='object')

In [59]:
Fifa_A2 = Fifa_MC2

Fifa_A2["Age"] = Fifa_Champions["Age"]
Fifa_A2["Wage (in euro)"] = Fifa_Champions["Wage(in Euro)"]
Fifa_A2["Release Clause"] = Fifa_Champions["Release Clause"]
Fifa_A2["Contract Until"] = Fifa_Champions["Contract Until"]

Fifa_A2

<ipython-input-59-eda9d163a80d>:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  Fifa_A2["Age"] = Fifa_Champions["Age"]
<ipython-input-59-eda9d163a80d>:4: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  Fifa_A2["Wage (in euro)"] = Fifa_Champions["Wage(in Euro)"]
<ipython-input-59-eda9d163a80d>:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  Fifa_A2["Release Clause"] = Fifa_Champions["Release Clause"]
<ipython-input-59-eda9d163a80d>:6: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  Fifa_A2["Contract Until"] = Fifa_Champions["Contract Until"]

,Known As,Overall,Potential,Real_OScore,Mean Overall,Club Name,Value(in Euro),Positions Played,Club Position,A1_Transfer?,Age,Wage (in euro),Release Clause,Contract Until
2,K. De Bruyne,91,91,91.0,85.666667,Manchester City,107500000,"CM,CAM",CM,False,31,350000,198900000,2025
5,Ederson,89,91,90.0,76.473684,Manchester City,88000000,GK,GK,False,28,210000,169400000,2026
6,Rúben Dias,88,91,89.5,80.083333,Manchester City,107500000,CB,CB,False,25,230000,206900000,2027
7,E. Haaland,88,94,91.0,79.454545,Manchester City,148000000,ST,ST,False,21,220000,303400000,2027
9,Bernardo Silva,88,88,88.0,84.000000,Manchester City,97500000,"CAM,CM",RW,False,27,260000,180400000,2025
10,João Cancelo,88,88,88.0,88.000000,Manchester City,82500000,"LB,RB",LB,False,28,250000,152600000,2027
14,Rodri,87,89,88.0,79.000000,Manchester City,88500000,CDM,CDM,False,26,200000,170400000,2027
18,R. Mahrez,86,86,86.0,84.500000,Manchester City,56500000,"RW,RM",SUB,False,31,220000,104500000,2025
19,A. Laporte,86,87,86.5,80.083333,Manchester City,64500000,CB,CB,False,28,195000,124200000,2025
24,İ. Gündoğan,85,85,85.0,73.555556,Manchester City,44000000,"CM,CDM",CM,False,31,185000,81400000,2023
25,K. Walker,85,85,85.0,76.000000,Manchester City,37500000,RB,RB,False,32,170000,69400000,2024
30,P. Foden,85,92,88.5,85.000000,Manchester City,109500000,"LW,CF,CAM",LW,False,22,180000,224500000,2024
35,J. Grealish,84,84,84.0,84.000000,Manchester City,46000000,"LW,LM,CAM",SUB,False,26,185000,85100000,2027
54,J. Stones,83,84,83.5,80.083333,Manchester City,34500000,CB,SUB,False,28,150000,66400000,2026
66,M. Akanji,81,82,81.5,80.083333,Manchester City,26500000,CB,SUB,False,26,120000,51000000,2023
71,K. Phillips,81,85,83.0,79.777778,Manchester City,32000000,"CDM,CM",SUB,False,26,120000,61600000,2028
77,S. Ortega,80,80,80.0,76.473684,Manchester City,14500000,GK,SUB,False,29,95000,26800000,2025
92,J. Álvarez,78,86,82.0,78.000000,Manchester City,32000000,"ST,RW,LW",SUB,False,22,100000,65599999,2027
95,N. Aké,78,80,79.0,72.500000,Manchester City,15000000,"CB,LB",SUB,False,27,95000,28900000,2025
118,Sergio Gómez,74,83,78.5,74.000000,Manchester City,9000000,"LB,RM,LM",SUB,False,21,53000,18500000,2026
147,C. Palmer,67,85,76.0,67.000000,Manchester City,2700000,"RW,CAM,CF",SUB,False,20,26000,6700000,2026
149,M. Rogers,66,82,74.0,71.333333,Manchester City,2200000,"LW,RW",RES,False,19,17000,5400000,2024
153,S. Carson,65,65,65.0,76.473684,Manchester City,80000,GK,SUB,True,36,11000,148000,2023
167,R. Lewis,61,82,71.5,76.000000,Manchester City,1000000,RB,SUB,True,17,650,2900000,2024
168,B. Knight,60,74,67.0,70.000000,Manchester City,600000,RW,RES,True,20,12000,1500000,2025
170,A. Robertson,58,78,68.0,79.857143,Manchester City,575000,CM,RES,True,19,8000,1600000,2023
171,J. Wilson-Esbrand,58,76,67.0,73.400000,Manchester City,500000,LB,RES,True,19,7000,1200000,2027

In [60]:
Fifa_CU = Fifa_A2[Fifa_A2['Contract Until'].isin(["2023","2024","2025"])]
Fifa_CU

,Known As,Overall,Potential,Real_OScore,Mean Overall,Club Name,Value(in Euro),Positions Played,Club Position,A1_Transfer?,Age,Wage (in euro),Release Clause,Contract Until
2,K. De Bruyne,91,91,91.0,85.666667,Manchester City,107500000,"CM,CAM",CM,False,31,350000,198900000,2025
9,Bernardo Silva,88,88,88.0,84.000000,Manchester City,97500000,"CAM,CM",RW,False,27,260000,180400000,2025
18,R. Mahrez,86,86,86.0,84.500000,Manchester City,56500000,"RW,RM",SUB,False,31,220000,104500000,2025
19,A. Laporte,86,87,86.5,80.083333,Manchester City,64500000,CB,CB,False,28,195000,124200000,2025
24,İ. Gündoğan,85,85,85.0,73.555556,Manchester City,44000000,"CM,CDM",CM,False,31,185000,81400000,2023
25,K. Walker,85,85,85.0,76.000000,Manchester City,37500000,RB,RB,False,32,170000,69400000,2024
30,P. Foden,85,92,88.5,85.000000,Manchester City,109500000,"LW,CF,CAM",LW,False,22,180000,224500000,2024
66,M. Akanji,81,82,81.5,80.083333,Manchester City,26500000,CB,SUB,False,26,120000,51000000,2023
77,S. Ortega,80,80,80.0,76.473684,Manchester City,14500000,GK,SUB,False,29,95000,26800000,2025
95,N. Aké,78,80,79.0,72.500000,Manchester City,15000000,"CB,LB",SUB,False,27,95000,28900000,2025
149,M. Rogers,66,82,74.0,71.333333,Manchester City,2200000,"LW,RW",RES,False,19,17000,5400000,2024
153,S. Carson,65,65,65.0,76.473684,Manchester City,80000,GK,SUB,True,36,11000,148000,2023
167,R. Lewis,61,82,71.5,76.000000,Manchester City,1000000,RB,SUB,True,17,650,2900000,2024
168,B. Knight,60,74,67.0,70.000000,Manchester City,600000,RW,RES,True,20,12000,1500000,2025
170,A. Robertson,58,78,68.0,79.857143,Manchester City,575000,CM,RES,True,19,8000,1600000,2023

In [61]:
age_threshold = 25
oscore_threshold = 5  # determine the difference from the mean that we will target.
mean_overall = Fifa_CU['Mean Overall']  # Store the mean overall in a variable for efficiency.

highlight_mask = (
    (Fifa_CU['Age'] > age_threshold) &  # Age condition
    (
        (abs(Fifa_CU['Real_OScore'] - mean_overall) <= oscore_threshold) |  # Real_OScore condition
        (Fifa_CU['Real_OScore'] < mean_overall)  # Include players with Real_OScore below the mean
    )
)

# Create a new column "A2_Transfer?" with True for the players we will transfer, and False otherwise.
Fifa_CU['A2_Transfer?'] = highlight_mask

Fifa_CU

<ipython-input-61-ee30d99e720a>:14: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  Fifa_CU['A2_Transfer?'] = highlight_mask

,Known As,Overall,Potential,Real_OScore,Mean Overall,Club Name,Value(in Euro),Positions Played,Club Position,A1_Transfer?,Age,Wage (in euro),Release Clause,Contract Until,A2_Transfer?
2,K. De Bruyne,91,91,91.0,85.666667,Manchester City,107500000,"CM,CAM",CM,False,31,350000,198900000,2025,False
9,Bernardo Silva,88,88,88.0,84.000000,Manchester City,97500000,"CAM,CM",RW,False,27,260000,180400000,2025,True
18,R. Mahrez,86,86,86.0,84.500000,Manchester City,56500000,"RW,RM",SUB,False,31,220000,104500000,2025,True
19,A. Laporte,86,87,86.5,80.083333,Manchester City,64500000,CB,CB,False,28,195000,124200000,2025,False
24,İ. Gündoğan,85,85,85.0,73.555556,Manchester City,44000000,"CM,CDM",CM,False,31,185000,81400000,2023,False
25,K. Walker,85,85,85.0,76.000000,Manchester City,37500000,RB,RB,False,32,170000,69400000,2024,False
30,P. Foden,85,92,88.5,85.000000,Manchester City,109500000,"LW,CF,CAM",LW,False,22,180000,224500000,2024,False
66,M. Akanji,81,82,81.5,80.083333,Manchester City,26500000,CB,SUB,False,26,120000,51000000,2023,True
77,S. Ortega,80,80,80.0,76.473684,Manchester City,14500000,GK,SUB,False,29,95000,26800000,2025,True
95,N. Aké,78,80,79.0,72.500000,Manchester City,15000000,"CB,LB",SUB,False,27,95000,28900000,2025,False
149,M. Rogers,66,82,74.0,71.333333,Manchester City,2200000,"LW,RW",RES,False,19,17000,5400000,2024,False
153,S. Carson,65,65,65.0,76.473684,Manchester City,80000,GK,SUB,True,36,11000,148000,2023,True
167,R. Lewis,61,82,71.5,76.000000,Manchester City,1000000,RB,SUB,True,17,650,2900000,2024,False
168,B. Knight,60,74,67.0,70.000000,Manchester City,600000,RW,RES,True,20,12000,1500000,2025,False
170,A. Robertson,58,78,68.0,79.857143,Manchester City,575000,CM,RES,True,19,8000,1600000,2023,False

In [63]:
"""

After this second analysis, we finaly decided to transfer those players :
Bernardo Silva - CAM, CM
R. Mahrez - RW, RM
M. Akanji - CB
S. Ortega - GK
S. Carson - GK


For the following reasons:

- Their contracts are ending in 2023, 2024 or 2025 so we can avoid the release clause.
- They are players older than 25, and we know that players have more potential when below 25 years.
- Their Real_OScore are the closest or below the Mean Overall of our Champions Leagues Top 10 teams.

"""

'\n\nAfter this second analysis, we finaly decided to transfer those players :\nBernardo Silva - CAM, CM\nR. Mahrez - RW, RM\nM. Akanji - CB\nS. Ortega - GK\n\n\nFor the following reasons:\n\n- Their contracts are ending in 2023, 2024 or 2025 so we can avoid the release clause.\n- They are players older than 25, and we know that players have more potential when below 25 years.\n- Their Real_OScore are the closest to the Mean Overall of our Champions Leagues Top 10 teams which takes into account their Overall and potential.\n\n'